name: Terafina
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Terafina Blog '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#515d60'
    - '#1c6c96'
    - '#4dbcc8'
    - '#404040'
    - '#000000'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
