name: Terafina
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#515d60'
    - '#1c6c96'
    - '#4dbcc8'
    - '#404040'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.8953409825917333
  rhythmicContrast: 0.75
purpose: []
